### PR TITLE
Error handling using promises

### PR DESCRIPTION
**Pull request by ghost**
Uses Promise instead of core.async channel for conveying result or error.
- [x] Wait for funcool/promesa release
- [x] Refactor
- [x] Upgrade dependencies
- [x] Update docs
- [x] Update examples

### CODE REVIEW

**Comment by niwinz** [comment]
:+1: waiting for it ;)

**Comment by ghost** [comment]
\o/ Still some refactoring to do, will ping you when it's ready!

**Comment by ghost** [comment]
@niwinz take a look and feel free to push to the branch any changes you see fit!

**Comment by niwinz** [comment]
It looks ok for the first iteration, later maybe I get some time for it an review it more deeply.
Thanks for the great work!

**Pull request merged**
